baseurl = "http://themindfulnest.co"
title = "The Mindful Nest"
theme = "editorial"
Paginate = 4

[Params]
  Title = "The Mindful Nest"
  NavTitle = "Content"
  FeaturedArticlesTitle = "Featured Articles"
  ContactTitle = "Contact"
  ContactDescription = "Here is how to get in touch"
  ContactEmail = "email@email.com"
  Copyright = "Monica Lent"

[taxonomies]
  tag = "tags"
  category = "categories"

[Permalinks]
  post = "/:filename/"

[[menu.main]]
 	name = "Style"
	url = "/"
	weight = 100

[[menu.main]]
 	name = "Fitness"
	url = "/"
	weight = 200

[[menu.main]]
 	name = "Food"
	url = "/"
	weight = 300

[[menu.main]]
 	name = "Creativity"
	url = "/"
	weight = 400

[[menu.main]]
 	name = "Home"
	url = "/"
	weight = 500
